baseURL = 'https://eidolaacademy.github.io/'
locale = 'en-us'
title = 'Eidola Academy'
theme = 'PaperMod'


[menu]
  [[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "新闻"
    url = "/news/"
    weight = 3
  [[menu.main]]
    name = "加入会员"
    url = "/join/"
    weight = 4
  [[menu.main]]
    name = "向Eidola提问"
    url = "/questions/"
    weight = 5

[markup.goldmark.renderer]
    unsafe = true

[params.label]
    text = "Eidola Academy"
    icon = "/images/eidola.ico"
    iconHeight = 35

[params]
    # 第一块：介绍
    homeIntroTitle = "Eidola Academy 👋"
    homeIntroBody = "欢迎来到 Eidola Academy。"

    # 第三块：行动/加入群聊
    homeActionTitle = "加入Eidola会员群"
    homeActionBody = "点击下方按钮加入会员社区。"
