baseURL = 'https://eidolaacademy.github.io/'
locale = 'en-us'
title = 'Eidola Academy'
theme = 'PaperMod'


[menu]
  [[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "博客"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "新闻"
    url = "/news/"
    weight = 3
  [[menu.main]]
    name = "资源"
    url = "/resource/"
    weight = 4
  [[menu.main]]
    name = "加入会员"
    url = "/join/"
    weight = 5
  [[menu.main]]
    name = "向Eidola提问"
    url = "/questions/"
    weight = 6

[markup.goldmark.renderer]
    unsafe = true

[params.label]
    text = "Eidola Academy"
    icon = "/images/eidola.ico"
    iconHeight = 35

[params]
    # 第一块：介绍
    homeIntroTitle = "Eidola Academy 👋"
    homeIntroBody = "欢迎来到 Eidola Academy。"

	# 【新增】第二块：每周分享
    homeShareTitle = "你愿意分享你这周做了什么吗？"
    homeShareBody = "欢迎给我发邮件，分享你这周做的最重要的事情。可以是一幅图，一个小视频，或者一个文档。"
    homeShareEmail = "eidola4ai@gmail.com"

    # 第三块：行动/加入群聊
    homeActionTitle = "加入Eidola会员群"
	homeActionImage = "/images/qr-code.png"
    # 或者如果支持 Markdown 语法
    homeActionContent = "![群聊二维码](/images/qr-code.png)"
